-- 윈도우 함수: 행과 행 간의 관계를 정의하기 위해 제공되는 함수
-- 순위, 합계, 평균, 행 위치 등을 조작할 수 있음
-- UNBOUNDED PRECEDING: 첫 번째 행
-- UNBOUNDED FOLLOWING: 마지막 행
-- TOTSAL에는 처음부터 마지막 행까지의 합계가 들어감
SELECT EMPNO, ENAME, SAL,
       SUM(SAL) OVER(ORDER BY SAL
                     ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) TOTSAL
  FROM EMP;
  
-- CURRUNT ROW: 현재 행
-- 처음부터 다음 행을 더하고 또 다음 행을 더해서 누적합 계산
SELECT EMPNO, ENAME, SAL,
       SUM(SAL) OVER(ORDER BY SAL
                     ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) TOTSAL
  FROM EMP;
  
-- 순위 함수: RANK,DENSE_RANK, ROW_NUMBER
SELECT ENAME, SAL, JOB,
       RANK() OVER(ORDER BY SAL DESC) ALL_RANK,
       RANK() OVER(PARTITION BY JOB ORDER BY SAL DESC) JOB_RANK
  FROM EMP;
  
SELECT ENAME, SAL, JOB,
       RANK() OVER(ORDER BY SAL DESC) ALL_RANK,
       DENSE_RANK() OVER(ORDER BY SAL DESC) DENSE_RANK,
       ROW_NUMBER() OVER(ORDER BY SAL DESC) ROW_NUMBER
  FROM EMP;
  
-- 집계 함수: SUM, AVG, COUNT, MAX, MIN
SELECT ENAME, MGR, SAL,
       SUM(SAL) OVER(PARTITION BY MGR) SUM_MGR
 FROM EMP;
 
-- 행 순서 관련 함수: FIRST_VALUE, LAST_VALUE, LAG, LEAD
-- FIRST_VALUE: 파티션에서 조회된 행 중에서 첫 번쨰 FETCH가 되는 행의 값을 출력
-- 부서별 급여가 가장 높은 사람을 추출
SELECT DEPTNO, ENAME, SAL,
       FIRST_VALUE(ENAME) OVER (PARTITION BY DEPTNO ORDER BY SAL DESC ROWS UNBOUNDED PRECEDING) AS DEPT_A
  FROM EMP;

-- LAST_VALUE: 파티션에서 마지막 행을 가지고 옴
-- BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING: 현재 행부터 마지막 행까지의 범위
SELECT DEPTNO, ENAME, SAL,
       LAST_VALUE(ENAME) OVER (PARTITION BY DEPTNO ORDER BY SAL DESC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS DEPT_A
  FROM EMP;
  
-- LAG: 이전 행의 값을 출력
SELECT DEPTNO, ENAME, SAL,
       LAG(SAL) OVER (ORDER BY SAL DESC) AS PRE_SAL
  FROM EMP;

-- LEAD: 지정한 위치의 행을 가져옴. 매개변수 중에서 2는 현재 행에서 2만큼 이동한 위치의 행을 출력, 음수값은 받지 않으며 기본값은 1이다.
SELECT DEPTNO, ENAME, SAL,
       LEAD(SAL, 2) OVER (ORDER BY SAL DESC) AS PRE_SAL
  FROM EMP;

-- 비율 관련 함수: CUME_DIST, PERCENT_RANK, NTITLE, RATIO_TO_REPORT
-- PERCENT_RANK: 파티션별로 0부터 1까지 누적 퍼센트를 출력
SELECT DEPTNO, ENAME, SAL, 
       ROUND(PERCENT_RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC), 2) AS PERCENT_SAL
  FROM EMP;
  
-- CUME_DIST: 첫 번째 행도 백분율에 적용시키고 누적 백분율을 출력
-- 누적백분율의 값은 0~1 사이의 값을 가짐
SELECT DEPTNO, ENAME, SAL,
       ROUND(CUME_DIST() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC), 2) AS PERCENT_SAL
  FROM EMP;
  
-- NTILE: 매개변수로 들어가는 정수값에 의해 행이 분할되어 출력. 행의 개수가 나누어 떨어지지 않을 경우 오라클 엔진이 알아서 분할함.
SELECT DEPTNO, ENAME, SAL, 
       NTILE(4) OVER (ORDER BY SAL DESC) AS N_TILE
  FROM EMP;